# Generated by Django 5.2.5 on 2025-08-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_type', models.CharField(choices=[('joy', 'Joy'), ('sadness', 'Sadness'), ('anger', 'Anger'), ('fear', 'Fear'), ('surprise', 'Surprise'), ('disgust', 'Disgust'), ('trust', 'Trust'), ('anticipation', 'Anticipation')], max_length=20)),
                ('intensity', models.IntegerField(default=5)),
                ('note', models.TextField(blank=True)),
                ('voice_note_url', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('activity', models.CharField(blank=True, max_length=100)),
                ('people', models.CharField(blank=True, max_length=100)),
                ('weather', models.CharField(blank=True, max_length=50)),
                ('physical_state', models.CharField(blank=True, max_length=50)),
                ('ai_analysis', models.JSONField(blank=True, default=dict)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('triggers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emotion',
                'verbose_name_plural': 'Emotions',
                'db_table': 'emotions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='emotions/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Emotion Image',
                'verbose_name_plural': 'Emotion Images',
                'db_table': 'emotion_images',
            },
        ),
    ]
