name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        cd moodcare-backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        cd moodcare-backend
        python manage.py test
    
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "$KEY" > private_key.pem
        chmod 600 private_key.pem
        
        # Deploy script
        ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER}@${HOST} << 'ENDSSH'
          # Navigate to project directory
          cd ~/moodcare/moodcare-backend
          
          # Pull latest changes
          git pull origin main
          
          # Activate virtual environment
          source venv/bin/activate
          
          # Install/update dependencies
          pip install -r requirements.txt
          
          # Run migrations
          python manage.py migrate --noinput
          
          # Collect static files
          python manage.py collectstatic --noinput
          
          # Check if tmux session exists
          tmux has-session -t moodcare 2>/dev/null
          
          if [ $? != 0 ]; then
            # Create new tmux session if it doesn't exist
            tmux new-session -d -s moodcare
          fi
          
          # Send commands to tmux session for zero-downtime deployment
          tmux send-keys -t moodcare C-c
          sleep 2
          tmux send-keys -t moodcare "source venv/bin/activate" Enter
          tmux send-keys -t moodcare "python manage.py runserver 0.0.0.0:8000" Enter
          
          echo "Deployment complete!"
        ENDSSH
        
        rm -f private_key.pem